spring.application.name=kiubitapi

# DB
spring.datasource.url=jdbc:mysql://localhost:3306/kiubit_schema_jpa?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# JWT
jwt.secret=Q2nQw2v5bVw6w8h9Jz6kP3nX2s5r8u1y4t7z0a6e9d3f2g5h8i1l4o7q0s3v6y9
jwt.expirationMs=3600000

# Port
server.port=8084